const topics = [
  {
    category: "Food",
    items: [
      { key: "Pho", value: "쌀국수" },
      { key: "Fried chicken", value: "치킨" },
      { key: "Fried rice", value: "볶음밥" },
      { key: "Ramen", value: "라멘" },
      { key: "Sandwich", value: "샌드위치" },
      { key: "Pizza", value: "피자" },
      { key: "Hamburger", value: "햄버거" },
      { key: "Tonkatsu", value: "돈까스" },
      { key: "okonomiyaki", value: "오꼬노미야끼" },
      { key: "Barbeque", value: "바베큐" },
    ],
  },
  {
    category: "Job",
    items: [
      { key: "athlete", value: "운동선수" },
      { key: "teacher", value: "교사" },
      { key: "Computer Programmer", value: "컴퓨터 프로그래머" },
      { key: "Babysitter", value: "베이비시터" },
      { key: "Dentist", value: "치과의사" },
      { key: "Police officer", value: "경찰" },
      { key: "Cook", value: "요리사" },
      { key: "teacher", value: "교사" },
      { key: "Actor", value: "연기자" },
      { key: "Designer", value: "디자이너" },
    ],
  },
  {
    category: "IceCream",
    items: [
      { key: "Ben & Jerry's", value: "밴 앤 제리스" },
      { key: "Häagen-Dazs", value: "하겐다즈" },
      { key: "Blizzard", value: "블리자드" },
      { key: "McFlurry", value: "맥플러리" },
      { key: "Sundae", value: "선데이" },
      { key: "Magnum", value: "매그넘" },
      { key: "Baskin Robbins", value: "배스킨라빈스" },
      { key: "Drum Stick", value: "드럼스틱" },
      { key: "Gelato", value: "젤라또" },
      { key: "Talenti", value: "탈렌티" },
    ],
  },
  {
    category: "MBTI",
    items: [
      { key: "ISTJ", value: "ISTJ" },
      { key: "ISTP", value: "ISTP" },
      { key: "ISFP", value: "ISFP" },
      { key: "ISFJ", value: "ISFJ" },
      { key: "INTP", value: "INTP" },
      { key: "INTJ", value: "INTJ" },
      { key: "INFP", value: "INFP" },
      { key: "INFJ", value: "INFJ" },
      { key: "ESTJ", value: "ESTJ" },
      { key: "ESTP", value: "ESTP" },
      { key: "ESFP", value: "ESFP" },
      { key: "ESFJ", value: "ESFJ" },
      { key: "ENTP", value: "ENTP" },
      { key: "ENTJ", value: "ENTJ" },
      { key: "ENFP", value: "ENFP" },
      { key: "ENFJ", value: "ENFJ" },
    ],
  },
  {
    category: "Fruit",
    items: [
      { key: "Apple", value: "사과" },
      { key: "Banana", value: "바나나" },
      { key: "Water melon", value: "수박" },
      { key: "Strawberry", value: "딸기" },
      { key: "Blueberry", value: "블루베리" },
      { key: "Orange", value: "오렌지" },
      { key: "DragonFruit", value: "용과" },
      { key: "Pineapple", value: "파인애플" },
      { key: "Mangosteen", value: "망고스틴" },
      { key: "Durian", value: "두리안" },
    ],
  },
  {
    category: "Sports",
    items: [
      { key: "SnowBoard", value: "스노우보드" },
      { key: "Soccer", value: "축구" },
      { key: "Basketball", value: "농구" },
      { key: "Baseball", value: "야구" },
      { key: "Golf", value: "골프" },
      { key: "Tennis", value: "테니스" },
      { key: "Hockey", value: "하키" },
      { key: "Bouldering", value: "볼더링" },
      { key: "Marathon", value: "마라톤" },
      { key: "Shooting", value: "사격" },
    ],
  },
  {
    category: "Christmas",
    items: [
      { key: "Santa Claus", value: "산타 클로스" },
      { key: "Rudolph", value: "루돌프" },
      { key: "Harry Potter", value: "해리포터" },
      { key: "Home Alone", value: "나 홀로 집에" },
      { key: "Carol", value: "캐롤" },
      { key: "Jesus", value: "예수님" },
      { key: "Frozen", value: "겨울왕국" },
      { key: "Snowman", value: "눈사람" },
      { key: "Chimney", value: "굴뚝" },
      { key: "Snow", value: "눈" },
    ],
  },
  {
    category: "Snack",
    items: [
      { key: "Reese's", value: "Reese's" },
      { key: "Cheetos", value: "치토스" },
      { key: "Choco Pie", value: "초코파이" },
      { key: "Oreo", value: "오레오" },
      { key: "Pocky", value: "포키" },
      { key: "M&M's", value: "M&M's" },
      { key: "Pringles", value: "프링글스" },
      { key: "Hershey's", value: "허쉬스" },
      { key: "Kit Kat", value: "킷켓" },
      { key: "Poptarts", value: "팝 타르트" },
    ],
  },
  {
    category: "Animal",
    items: [
      { key: "Dog", value: "강아지" },
      { key: "Cat", value: "고양이" },
      { key: "Shark", value: "상어" },
      { key: "Eagle", value: "독수리" },
      { key: "Snake", value: "뱀" },
      { key: "Sparrow", value: "참새" },
      { key: "Salmon", value: "연어" },
      { key: "Giraffe", value: "기린" },
      { key: "Deer", value: "사슴" },
      { key: "Turtle", value: "거북" },
    ],
  },
];
let topicArr = [];
for (let i = 0; i < topics.length; i++) {
  topicArr.push(topics[i].category);
}
